=== welle/DB2POPO/datamodel/datamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>

 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="MODEL">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>  

	<xs:simpleType name="NonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value=".*[^\s].*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
      		<xs:enumeration value="int"/>
      		<xs:enumeration value="boolean"/>
      		<xs:enumeration value="blob"/>
      		<xs:enumeration value="datetime"/>
      		<xs:enumeration value="float"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ASBTRACTDATAMODEL">
		<xs:complexContent>
			<xs:extension base="MODEL">
				<xs:sequence>
   					<xs:element name="NODE" maxOccurs="unbounded" minOccurs="1">
     					<xs:complexType>
		    				<xs:attribute name="name" type="NonEmptyString" use="required"/>
        					<xs:attribute name="type" type="NonEmptyStringType" use="required"/>
        					<xs:attribute name="nullable" type="xs:boolean" use="required"/>
        					<xs:attribute name="autoincrement" type="xs:boolean" use="required"/>
        					<xs:attribute name="pk" type="xs:boolean" use="required"/>
        					<xs:attribute name="lenght" type="xs:integer" use="required"/>
     					</xs:complexType>
   					</xs:element>
   				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>  
	
	<xs:element name="DATAMODEL" type="ASBTRACTDATAMODEL"></xs:element>
</xs:schema>

=== welle/DB2POPO/datamodel/taxmapping.xml
<DATAMODEL name="taxmapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="taxCode" type="string" nullable="false" autoincrement="false" lenght="10"/>
    		<NODE name="companyId" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="flagExport" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="flagExcluded" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="flagInactive" type="string" nullable="false" autoincrement="false" lenght="1"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/paymentaccount.xml
<DATAMODEL name="paymentaccount" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="number" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="exercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="inputAccess" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="outputAccess" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="type" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="sortCode" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="accountNumber" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="iban" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="bic" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="swift" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="address" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="postalCode" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="town" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="country" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/articlepicture.xml
<DATAMODEL name="articlepicture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idArticlePicture" type="int" nullable="false" autoincrement="true" lenght="11"/>
    		<NODE name="idArticle" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="locale" type="string" nullable="true" autoincrement="false" lenght="50"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="1000"/>
    		<NODE name="picture" type="blob" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="pictureThumbnail" type="blob" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="pictureMedium" type="blob" nullable="false" autoincrement="false" lenght="19"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/payment.xml
<DATAMODEL name="payment" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="paymentName" type="string" nullable="false" autoincrement="false" lenght="30"/>
    		<NODE name="companyId" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="exercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="ownerModule" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="ownerModuleFunction" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="startDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="closingDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="displayDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="state" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="subState" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="logNumber" type="int" nullable="true" autoincrement="false" lenght="8"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="4000"/>
    		<NODE name="customerId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="payerRef" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="accountExercise" type="int" nullable="true" autoincrement="false" lenght="4"/>
    		<NODE name="paymentAccount" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="paymentContact" type="int" nullable="true" autoincrement="false" lenght="8"/>
    		<NODE name="paymentType" type="string" nullable="false" autoincrement="false" lenght="2"/>
    		<NODE name="currencyCode" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="priceInCurrency" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="priceInCompanyCurrency" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="original" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="vatPeriod" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="flgIsBatch" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="costsType" type="string" nullable="true" autoincrement="false" lenght="3"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/jobs.xml
<DATAMODEL name="jobs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="jobName" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="idContact" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="idContactContract" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="contractCode" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="idUserContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="creationDate" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="state" type="int" nullable="false" autoincrement="false" lenght="2"/>
    		<NODE name="idCatalog" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="idArticle" type="int" nullable="true" autoincrement="false" lenght="11"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/tag.xml
<DATAMODEL name="tag" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idTag" type="int" nullable="false" autoincrement="true" lenght="11"/>
    		<NODE name="idTagCategory" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="shortName" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="longName" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="type" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="pk" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="constraints" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/taskmessage.xml
<DATAMODEL name="taskmessage" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idTaskMessage" type="int" nullable="false" autoincrement="true" lenght="11"/>
    		<NODE name="senderContactId" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="sentDate" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="dueDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="message" type="string" nullable="false" autoincrement="false" lenght="500"/>
    		<NODE name="type" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="docReference" type="string" nullable="true" autoincrement="false" lenght="500"/>
    		<NODE name="status" type="int" nullable="false" autoincrement="false" lenght="11"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/statement.xml
<DATAMODEL name="statement" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idStatement" type="int" nullable="false" autoincrement="true" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="account" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="accountExercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="statementDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="reference" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="openingBalance" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="closingBalance" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="movement" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="reconciliedAmount" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="difference" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="status" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="type" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>
