=== welle/DB2POPO/datamodel/datamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>

 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="MODEL">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>  

	<xs:simpleType name="NonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value=".*[^\s].*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
      		<xs:enumeration value="int"/>
      		<xs:enumeration value="boolean"/>
      		<xs:enumeration value="blob"/>
      		<xs:enumeration value="datetime"/>
      		<xs:enumeration value="float"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ASBTRACTDATAMODEL">
		<xs:complexContent>
			<xs:extension base="MODEL">
				<xs:sequence>
   					<xs:element name="NODE" maxOccurs="unbounded" minOccurs="1">
     					<xs:complexType>
		    				<xs:attribute name="name" type="NonEmptyString" use="required"/>
        					<xs:attribute name="type" type="NonEmptyStringType" use="required"/>
        					<xs:attribute name="nullable" type="xs:boolean" use="required"/>
        					<xs:attribute name="autoincrement" type="xs:boolean" use="required"/>
        					<xs:attribute name="pk" type="xs:boolean" use="required"/>
        					<xs:attribute name="lenght" type="xs:integer" use="required"/>
     					</xs:complexType>
   					</xs:element>
   				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>  
	
	<xs:element name="DATAMODEL" type="ASBTRACTDATAMODEL"></xs:element>
</xs:schema>

=== welle/DB2POPO/datamodel/contactaddress.xml
<DATAMODEL name="contactaddress" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idAddress" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="validityTo" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="address1" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="address2" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="address3" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="address4" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="streetName" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="streetNumber" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="postalCode" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="town" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="county" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="country" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="addressType" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="category" type="string" nullable="false" autoincrement="false" lenght="10"/>
    		<NODE name="longitude" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="latitude" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="centreLongitude" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="centreLatitude" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="scale" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="mapType" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="isoCountry" type="string" nullable="true" autoincrement="false" lenght="3"/>
    		<NODE name="postbox" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contactdashwidget.xml
<DATAMODEL name="contactdashwidget" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="dashboardName" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="widgetName" type="string" nullable="false" autoincrement="false" lenght="255"/>
    		<NODE name="gridX" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="gridY" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="weightX" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="weightY" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="gridWidth" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="gridHeight" type="int" nullable="false" autoincrement="false" lenght="11"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/algorithm.xml
<DATAMODEL name="algorithm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="algorithmName" type="string" nullable="false" autoincrement="false" lenght="100"/>
    		<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="validityTo" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="roundoff" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="idActionTarget" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="text" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="definition" type="string" nullable="true" autoincrement="false" lenght="10000"/>
    		<NODE name="dependencies" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="result" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="printoutCode" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="printoutType" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="ledger" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="adding" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="account" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="finalAlgo" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="periodical" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="returnType" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="abstractFlag" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="writableFlag" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="idempotentFlag" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="codeId" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="idAlgorithmCategory" type="int" nullable="false" autoincrement="false" lenght="11"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/invoicelog.xml
<DATAMODEL name="invoicelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="invoiceName" type="string" nullable="false" autoincrement="false" lenght="30"/>
    		<NODE name="companyId" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="logNumber" type="int" nullable="false" autoincrement="false" lenght="8"/>
    		<NODE name="lineNumber" type="int" nullable="true" autoincrement="false" lenght="4"/>
    		<NODE name="batchNumber" type="string" nullable="true" autoincrement="false" lenght="30"/>
    		<NODE name="state" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="subState" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="timeStamp" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="startDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="expectedDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="fieldName" type="string" nullable="true" autoincrement="false" lenght="30"/>
    		<NODE name="oldValue" type="string" nullable="true" autoincrement="false" lenght="30"/>
    		<NODE name="newValue" type="string" nullable="true" autoincrement="false" lenght="30"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contactemployee.xml
<DATAMODEL name="contactemployee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="validityTo" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="dateOfBirth" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="sex" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="maritalStatus" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="nationality" type="string" nullable="true" autoincrement="false" lenght="3"/>
    		<NODE name="townOfBirth" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contactlogin.xml
<DATAMODEL name="contactlogin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="name" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="login" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="password" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="email" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="roles" type="string" nullable="true" autoincrement="false" lenght="500"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/accountperiodtotal.xml
<DATAMODEL name="accountperiodtotal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="accountNumber" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="exercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="currencyIsoCode" type="string" nullable="false" autoincrement="false" lenght="10"/>
    		<NODE name="periodId" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="debit" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="credit" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitBlocked" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditBlocked" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitPaid" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditPaid" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitManual" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditManual" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitInvoice" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditInvoice" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitPaidDraft" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditPaidDraft" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitManualDraft" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditManualDraft" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="debitInvoiceDraft" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="creditInvoiceDraft" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="transactionCounter" type="int" nullable="true" autoincrement="false" lenght="11"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contactopenid.xml
<DATAMODEL name="contactopenid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="openId" type="string" nullable="false" autoincrement="false" lenght="255"/>
    		<NODE name="openIdType" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="displayName" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="roles" type="string" nullable="true" autoincrement="false" lenght="500"/>
    </DATAMODEL>
