=== welle/DB2POPO/datamodel/datamodel.xsd
<?xml version="1.0" encoding="UTF-8"?>

 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="MODEL">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>  

	<xs:simpleType name="NonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value=".*[^\s].*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="NonEmptyStringType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string"/>
      		<xs:enumeration value="int"/>
      		<xs:enumeration value="boolean"/>
      		<xs:enumeration value="blob"/>
      		<xs:enumeration value="datetime"/>
      		<xs:enumeration value="float"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ASBTRACTDATAMODEL">
		<xs:complexContent>
			<xs:extension base="MODEL">
				<xs:sequence>
   					<xs:element name="NODE" maxOccurs="unbounded" minOccurs="1">
     					<xs:complexType>
		    				<xs:attribute name="name" type="NonEmptyString" use="required"/>
        					<xs:attribute name="type" type="NonEmptyStringType" use="required"/>
        					<xs:attribute name="nullable" type="xs:boolean" use="required"/>
        					<xs:attribute name="autoincrement" type="xs:boolean" use="required"/>
        					<xs:attribute name="pk" type="xs:boolean" use="required"/>
        					<xs:attribute name="lenght" type="xs:integer" use="required"/>
     					</xs:complexType>
   					</xs:element>
   				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>  
	
	<xs:element name="DATAMODEL" type="ASBTRACTDATAMODEL"></xs:element>
</xs:schema>

=== welle/DB2POPO/datamodel/contract.xml
<DATAMODEL name="contract" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="code" type="string" nullable="false" autoincrement="false" lenght="10"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="validityTo" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="algorithmName" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="queryDefinition" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="periodicity" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="text" type="string" nullable="true" autoincrement="false" lenght="19"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contact.xml
<DATAMODEL name="contact" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="validityTo" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="contactCode" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="title" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="name1" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="name2" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="name3" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="abbreviation" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="entityType" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="entitySubType" type="string" nullable="false" autoincrement="false" lenght="5"/>
    		<NODE name="category" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="temporary" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="language" type="string" nullable="true" autoincrement="false" lenght="5"/>
    		<NODE name="contactPerson" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="locale" type="string" nullable="true" autoincrement="false" lenght="5"/>
    		<NODE name="comments" type="string" nullable="true" autoincrement="false" lenght="4000"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contactthirdpartybanking.xml
<DATAMODEL name="contactthirdpartybanking" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContactThirdPartyBanking" type="int" nullable="false" autoincrement="true" lenght="11"/>
    		<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="address" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="postCode" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="town" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="iban" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="bic" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="account" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="owner" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="paymentForm" type="string" nullable="true" autoincrement="false" lenght="1"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/secondarycoa.xml
<DATAMODEL name="secondarycoa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idSecondaryCOA" type="int" nullable="false" autoincrement="true" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="accountExercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="name" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="title" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="linkedApplication" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="compFlag" type="string" nullable="false" autoincrement="false" lenght="1"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/invoice.xml
<DATAMODEL name="invoice" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="invoiceName" type="string" nullable="false" autoincrement="false" lenght="30"/>
    		<NODE name="companyId" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="invoiceExercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="ownerModule" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="ownerModuleFunction" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="startDate" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="closingDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="deadlineDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="expectedDate" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="state" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="subState" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="4000"/>
    		<NODE name="comments" type="string" nullable="true" autoincrement="false" lenght="4000"/>
    		<NODE name="customerRef" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="customerId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="businessUnitId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="invoiceAddressId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="invContactId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="invContactAddressId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="deliveryAddressId" type="int" nullable="true" autoincrement="false" lenght="8"/>
    		<NODE name="delContactId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="delContactAddressId" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="businessContact" type="string" nullable="true" autoincrement="false" lenght="30"/>
    		<NODE name="technicalContact" type="string" nullable="true" autoincrement="false" lenght="30"/>
    		<NODE name="defaultTaxCode" type="string" nullable="true" autoincrement="false" lenght="5"/>
    		<NODE name="vatIncluded" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="currencyCode" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="priceInCurrency" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="priceInCompanyCurrency" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="vatAmountInCurrency" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="vatAmountInCompanyCurrency" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="original" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="lastReminder" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="alreadyPaidAmount" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="flgManualDeadline" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="paymentAccount" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="reference" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="vatPeriod" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="accountExercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="invoiceType" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="jobNumber" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="thirdPartyBank" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="format" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="parentInvoice" type="string" nullable="true" autoincrement="false" lenght="30"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/account.xml
<DATAMODEL name="account" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="number" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="exercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="name" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="taxCode" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="parentAccountNumber" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="sortNumber" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="currencyCode" type="string" nullable="false" autoincrement="false" lenght="10"/>
    		<NODE name="status" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="carryForward" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="reconcile" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="linkedAccount" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="zeroBalance" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="type" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="manual" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="category" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/accountline.xml
<DATAMODEL name="accountline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="ledgerName" type="string" nullable="false" autoincrement="false" lenght="45"/>
    		<NODE name="exercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="lineNumber" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="subLineNumber" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="debitCredit" type="string" nullable="false" autoincrement="false" lenght="1"/>
    		<NODE name="transactionDate" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="jobNumber" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="businessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="account" type="string" nullable="false" autoincrement="false" lenght="20"/>
    		<NODE name="counterpartBU" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="counterpartAccount" type="string" nullable="true" autoincrement="false" lenght="20"/>
    		<NODE name="accountExercise" type="int" nullable="false" autoincrement="false" lenght="4"/>
    		<NODE name="amount" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="description" type="string" nullable="true" autoincrement="false" lenght="4000"/>
    		<NODE name="reference" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="vatCode" type="string" nullable="true" autoincrement="false" lenght="10"/>
    		<NODE name="vatIncluded" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="vatRate" type="float" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="draft" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="state" type="int" nullable="true" autoincrement="false" lenght="2"/>
    		<NODE name="vatPeriod" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="idStatement" type="int" nullable="true" autoincrement="false" lenght="11"/>
    </DATAMODEL>

=== welle/DB2POPO/datamodel/contactemployeeswiss.xml
<DATAMODEL name="contactemployeeswiss" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datamodel.xsd">
			<NODE name="idContact" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="idBusinessUnit" type="int" nullable="false" autoincrement="false" lenght="11"/>
    		<NODE name="validityFrom" type="datetime" nullable="false" autoincrement="false" lenght="19"/>
    		<NODE name="validityTo" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="numAVS" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="permitType" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="permitNumber" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="permitExpiry" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="oldAVS" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="unknownAVS" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="drivingPermitType" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="drivingPermitNumber" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="drivingPermitObtention" type="datetime" nullable="true" autoincrement="false" lenght="19"/>
    		<NODE name="jobLocation" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="function" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="nbHoursPerWeek" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="nbHolidays" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="occupationRate" type="int" nullable="true" autoincrement="false" lenght="11"/>
    		<NODE name="unitHolidays" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="bankName" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="bankAddress" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="bankPostCode" type="string" nullable="true" autoincrement="false" lenght="45"/>
    		<NODE name="bankTown" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="bankIban" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="bankAccount" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="bankAccountOwner" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="bankAccountOwnerAddress" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="postAccountNumber" type="string" nullable="true" autoincrement="false" lenght="100"/>
    		<NODE name="postAccountOwner" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="postAccountOwnerAddress" type="string" nullable="true" autoincrement="false" lenght="255"/>
    		<NODE name="paymentForm" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="paymentType" type="string" nullable="true" autoincrement="false" lenght="1"/>
    		<NODE name="bankBic" type="string" nullable="true" autoincrement="false" lenght="45"/>
    </DATAMODEL>
